### PR TITLE
Time Sleep: Constants and Memory Issue

### PR DESCRIPTION
**Pull request by torch2424**
continuation of #11 

This implement's @jedisct1 's suggestion of using a constant to specify the time for sleep 😄

Also, this moves around the `neventsBuffer`. The reason being is that this inherently will not work in a while true loop 😢 If we make the `neventsBuffer` a long lived static, the pointer can change, and will cause an error. And if we repedetly create it, this creates a memory leak, but also will cause an error of future unrelated allocations 😢 

My apologies on merging this in! I thought it was working, but as I started stress testing and investigating, I realized these issues are with the runtime.

Everything works fine (But infinitely grows) by using `--runtime stub`. 

cc @MaxGraey @dcodeIO

### CODE REVIEW

**Comment by dcodeIO** [comment]
The stub runtime can undo the respective top-most allocation by means of `__free`:

```ts
var ptr = __alloc(...); // manual allocation is not refcounted
// do something
__free(ptr);
```

This also works with multiple allocs while the free'd one is the latest allocated. Perhaps that helps? :)

**Comment by dcodeIO** [comment]
Perhaps it's also a good idea to check that an event happened, like so

```ts
let neventsBuffer = __alloc(4, 0);
do {
  poll_oneoff(
    changetype<usize>(clockSub),
    changetype<usize>(clockEvent),
    1,
    neventsBuffer
  );
} while (load<i32>(neventsBuffer) < 1); // repeat until an event is received
__free(neventsBuffer);
```

**Comment by MaxGraey** [comment]
Also rust's [thread.sleep wasi implementation](https://github.com/fsyncd/rust/blob/master/src/libstd/sys/wasi/thread.rs#L26) used monotonic clock, not realtime

**Comment by jedisct1** [comment]
I'm guilty for the Rust implementation. Is the fact that it's using a monotonic clock an issue?

**Comment by MaxGraey** [comment]
haha, no. I just wonder which is better (right?) approach? realtime or monotonic?

**Comment by MaxGraey** [comment]
btw I guess it should be CLOCKID_PROCESS_CPUTIME or CLOCKID_THREAD_CPUTIME

**Comment by jedisct1** [comment]
`CLOCKID_PROCESS_CPUTIME` and `CLOCKID_THREAD_CPUTIME` are only used to count processor time. That doesn't match the `sleep()` semantics.

`CLOCKID_MONOTONIC` is probably fine here. `REALTIME` would suggest `sleep()` is not affected by the system being put to sleep/hibernation, but this is the case.

**Comment by MaxGraey** [comment]
okey, good to know!

**Comment by torch2424** [comment]
@dcodeIO 

> In general, if there is a manual __alloc somewhere, there should always be a __free afterwards since manual allocations are not refcounted unless changetyped. Works very much like malloc and free while it's usize.

So remember we had chatted about free'ing the `neventsBuffer`? It ended up also having a bug 😂 I'll take some time soon to get like an isolated test case we can all take a look at, as I think I went through all the possible implementations I could go through to try to get this to work without running into a garbage collector conflict. 😄 

And in my use case, I can use stub, but I do definitely want to use the full runtime, as everything else would not be fun to manage myself (the runtime has me spoiled now 😂).

@MaxGraey @jedisct1 

Oh nnice glad I chose the right clock 😂 I didn't have a super strong opinion on it, just made more sense, glad I guessed right haha! And thanks for looking into Rust's implementation @MaxGraey ! 😄 👍

**Pull request merged**
